working on osx

diff --git a/uni-q b/uni-q
--- a/uni-q
+++ b/uni-q
@@ -74,8 +74,8 @@ function find_a_hasher() {
 #############################################################################
 # The Program!
 
-if ! mkdir ${PROCESS_LOCK_DIR} > /dev/null 2>&1; then
-  die "Unable to acquire lock" $ERR_LOCK
+if ! mkdir -p ${PROCESS_LOCK_DIR} > /dev/null 2>&1; then
+  die "Unable to acquire lock ${PROCESS_LOCK_DIR}" $ERR_LOCK
 fi
 
 # clean up our lock on exit
@@ -112,8 +112,14 @@ function process_queue() {
 }
 
 function export_environment(){
-  # rewrite our environment as a series of variable declarations followed by their associated exports
-  env | cut -f 1,2- --output-delimiter="=" -d= | sed -r -e "s[(^\w*)=(.*$)[\1='\2'; export \1;[g"
+  if echo ${OSTYPE} | grep darwin
+  then
+    # rewrite our environment as a series of variable declarations followed by their associated exports
+    env | cut -f 1,2- --output-delimiter="=" -d= | sed -E -e 's|^(.*)=(.*)$|export \1="\2";|g'
+  else
+    # rewrite our environment as a series of variable declarations followed by their associated exports
+    env | cut -f 1,2- --output-delimiter="=" -d= | sed -r -e "s[(^\w*)=(.*$)[\1='\2'; export \1;[g"
+  fi
 }
 
 function generate_queue_stamp(){
