adding unique check, moving enqueued timestamp

diff --git a/uni-q b/uni-q
--- a/uni-q
+++ b/uni-q
@@ -7,6 +7,9 @@ QUEUE_DIR="${WORKING_DIR}/queue"
 
 #############################################################################
 ## Utils
+function error(){ echo $1 >&2; }
+function die(){ echo $1 >&2;  exit $2; }
+
 function hash_with_shasum() {
   if which shasum > /dev/null 2>&1 ; then
     function hasher() {
@@ -63,7 +66,7 @@ function find_a_hasher() {
 #############################################################################
 # The Program!
 if ! find_a_hasher ; then
-  echo 'I could not find a hash provider!'
+  error 'I could not find a hash provider!'
   exit 1
 fi
 
@@ -71,12 +74,11 @@ mkdir -p "$LOGGING_DIR"
 mkdir -p "$QUEUE_DIR"
 
 function process_queue() {
-  QUEUE_DIR="${1}"
-  LOG_DIR="${2}"
+  local QUEUE_DIR="${1}"
+  local LOG_DIR="${2}"
   DID_SOMETHING=
-  echo "processing queue"
-  pushd $QUEUE_DIR > /dev/null 2>&1
-  for command in $QUEUE_DIR/*
+  echo "processing queue: ${QUEUE_DIR}"
+  for command in ${QUEUE_DIR}/*
   do
     [ -x "${command}" ] || continue
     FILE_NAME=$(basename "${command}")
@@ -84,6 +86,7 @@ function process_queue() {
     echo "*** start " $(date +"%x %X") '****************************************' >> ${LOG_FILE}
     $command >> ${LOG_FILE} 2>&1
     echo "*** end " $(date +"%x %X") '****************************************' >> ${LOG_FILE}
+    DID_SOMETHING=YES
   done
   [ -z "$DID_SOMETHING" ] && return 1
   return 0
@@ -95,32 +98,33 @@ function export_environment(){
 }
 
 function enqueue_command(){
-  COMMAND="${1}"
-  echo "enqueuing command:"
-  echo "${1}"
+  local COMMAND="${1}"
+  local QUEUE_DIR="${2}"
   if [ -x "$COMMAND" ]; then
     # we have a file
     FILE_NAME=${QUEUE_DIR}/$(echo $COMMAND | sed -e 's[\/[_[g')
-    echo "### enqueued " $(date +"%x %X") > $FILE_NAME
+    [ -x "$FILE_NAME" ] && die "command already queued" 4
     export_environment >> $FILE_NAME
     echo $COMMAND >> $FILE_NAME
+    echo "### enqueued " $(date +"%x %X") >> $FILE_NAME
   else
     # it's on stdin
     TEMP_FILE=$(mktemp)
     trap "[ -f \"$TEMP_FILE\" ] && rm $TEMP_FILE" EXIT
-    echo "### enqueued " $(date +"%x %X") > $TEMP_FILE
     export_environment >> $TEMP_FILE
     cat >> $TEMP_FILE
     FILE_NAME=${QUEUE_DIR}/$(hasher $TEMP_FILE)
+    [ -x "$FILE_NAME" ] && die "command already queued" 4
+    echo "### enqueued " $(date +"%x %X") >> $TEMP_FILE
     mv "$TEMP_FILE" "$FILE_NAME"
   fi
   chmod +x $FILE_NAME
-  echo "file: " $FILE_NAME
+  echo "command queued"
 }
 
 case "${1}" in
   "process")
-    process_queue
+    process_queue ${QUEUE_DIR} ${LOGGING_DIR}
     exit
     ;;
   *)
@@ -129,13 +133,11 @@ case "${1}" in
       # get us an absolute path to the command
       [[ "${COMMAND}" == \/* ]] || COMMAND=$(pwd)/${COMMAND}
     elif [ -n "${1}" ]; then
-      echo "The parameter provided doesn't appear to refer to a an executable file" >&2
-      echo "You gave me: ${1}" >&2
-      exit 1
+      error "The parameter provided doesn't appear to refer to a an executable file"
+      die "You gave me: ${1}" 1
     else
       if [ -t 0 ]; then
-        echo "You need to provide a command either via stdin or as file on the command line." >&2
-        exit 2
+        die "You need to provide a command either via stdin or as file on the command line." 2
       fi
       # last place to look for a command is stdin
       if read -t 0; then
@@ -143,11 +145,9 @@ case "${1}" in
       fi
     fi
     if [ -z "${COMMAND}" ]; then
-      echo "I could not find any commands, sorry" >&2
-      exit 3
+      die "I could not find any commands, sorry" 3
     fi
-    enqueue_command "${COMMAND}"
+    enqueue_command "${COMMAND}" "${QUEUE_DIR}"
     exit
     ;;
 esac
-
